### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by marcelloh** [resotto/gochk#4]
go get -u github.com/resotto/gochk
```
package github.com/resotto/gochk: no Go files in /Users/marcelloh/go/src/github.com/resotto/gochk
```
go run cmd/gochk/main.go
```
cmd/gochk/main.go:25:2: use of internal package github.com/resotto/gochk/internal/gochk
```
It would be nice if I could compile it :-(

**Comment by resotto** [comment]
@marcelloh So Sorry for my late replying. 
I'll investigate it. Thank you for your notifying me.

**Comment by resotto** [comment]
@marcelloh 
This is the expected result so this is ok.
> package github.com/resotto/gochk: no Go files in /Users/marcelloh/go/src/github.com/resotto/gochk

However, I have no idea why you got the messege when running Gochk:
> cmd/gochk/main.go:25:2: use of internal package github.com/resotto/gochk/internal/gochk

Please give me full error message or details?
Thanks.

**Comment by resotto** [comment]
@marcelloh If you have any updates, please reopen this issue.

**Comment by marcelloh** [comment]
the second error was, when i got the project fro github and tried to compile it.
Since it's somekind of library, I think it should be compilable,  not run like you suggest.

But now I do it the way the instructions are:
```
go run cmd/gochk/main.go -t=/users/marcelloh/data/go-private/CleanToDo

**Comment by marcelloh** [comment]
so what I did:
moved the internal/gochck to internal_gochk
moved main.go to the root
build it: go build -o gochck . 
and now I have an executable gochk

**Comment by resotto** [comment]
@marcelloh If you want the binary of Gochk, please run following instruction:

https://github.com/resotto/gochk#installation

**Comment by resotto** [comment]
@marcelloh If you have any updates, please reopen this.
