### ISSUE TITLE
it hangs

### ISSUE THREAD

**Issue by marcelloh** [resotto/gochk#5]
when I have a non -go file in the destination directory, it hangs
.golangci.yml
I changed the Check a bit to see what it does
```
		fileName := info.Name()
		log.Printf("read.go:109 fileName %#v\n", fileName)

		if info.IsDir() || fileName[len(fileName)-3:] != ".go" {
			return nil
		}

```
This will fix it (because it's now only looking at *.go files

Ps. Did you know you can detect all the imports via AST rather than the string stuff you do?

**Comment by resotto** [comment]
@marcelloh Sorry, current version seek `.go` first, so your file **`.go`**`langci.yml` was treated as `.go` file.
I'll fix it.

Thank you so much.

**Comment by resotto** [comment]
@marcelloh Thank you for your teaching.
 Oh, no! You mean AST as Abstract Syntax Tree? and we can fetch imports via [`go/ast` package](https://golang.org/pkg/go/ast/)??

This will make Gochk so simple (and more needless??).
I'll rethink the whole application design. Thank you so much.

**Comment by marcelloh** [comment]
I can give you a hint in how this works.
This is part of my static analyser:

func Check(fileSet *token.FileSet, file string, node *ast.File) {

for _, decl := range node.Decls {
genDecl, ok := decl.(*ast.GenDecl)
if !ok || genDecl.Tok != token.IMPORT {
continue
}

for _, spec := range genDecl.Specs {
importSpec := spec.(*ast.ImportSpec)
impName := importSpec.Path.Value
impName = strings.ReplaceAll(impName, `"`, "")
// do something here
}
}
}


Op wo 11 nov. 2020 om 16:19 schreef resotto <notifications@github.com>:

**Comment by resotto** [comment]
@marcelloh Thank you so much for your advice.
I enhanced Gochk to use AST for parsing file imports.
